---
name: Unittests
'on':
  pull_request:
  push:
    branches:
      - main
      - ci-test

jobs:
  test:
    name: Unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install coverage
        run: pip install coverage

      - name: Run unit tests
        run: coverage run -m unittest discover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
...